pipeline {
    agent any

    environment {
        IMAGE_NAME = "xavidocker99/ca6-app:latest"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/1240598Rafa/cogsi2526-1240598-1240601.git'
            }
        }

        stage('Assemble') {
            steps {
                dir('CA2/Part2') {
                    bat 'gradlew.bat clean assemble -x test'
                }
            }
        }

        stage('Tests') {
            parallel {

                stage('Unit Tests') {
                    steps {
                        dir('CA2/Part2') {
                            bat 'gradlew.bat test --tests *Unit*'
                        }
                    }
                }

                stage('Integration Tests') {
                    steps {
                        dir('CA2/Part2') {
                            bat 'gradlew.bat test --tests *Integration*'
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                bat "docker build -t %IMAGE_NAME% CA6/Part2"
            }
        }

        stage('Tag Docker Image') {
            steps {
                bat "docker tag %IMAGE_NAME% %IMAGE_NAME%"
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-username',
                        usernameVariable: 'USER',
                        passwordVariable: 'PASS'
                    )
                ]) {
                    bat "docker login -u %USER% -p %PASS%"
                    bat "docker push %IMAGE_NAME%"
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'CA6/Part2/Dockerfile', allowEmptyArchive: true
            }
        }

        stage('Deploy to Production') {
            when {
                branch 'main'
            }
            steps {
                bat "ansible-playbook -i ansible/hosts.ini ansible/deploy.yml"
            }
        }
    }

    post {
        success {
            echo "Build and deployment completed successfully!"
        }
        failure {
            echo "Pipeline FAILED!"
        }
    }
}
