pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git(
                    branch: 'ca6-part1',
                    url: 'https://github.com/1240598Rafa/cogsi2526-1240598-1240601.git',
                    credentialsId: 'github-pat'
                )
            }
        }

        stage('Assemble') {
            steps {
                dir('CA6/Part1/spring-app') {
                    sh './gradlew clean build'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CA6/Part1/spring-app') {
                    sh './gradlew test'
                }
            }
            post {
                always {
                    junit 'CA6/Part1/spring-app/build/test-results/test/*.xml'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'CA6/Part1/spring-app/build/libs/*.jar', fingerprint: true
            }
        }

        stage('Deploy to Production?') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    input message: "Deploy to GREEN VM?"
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('CA6/Part1') {
                    sh "vagrant provision green"
                }
            }
        }

        stage('Health Check') {
            steps {
                script {
                    def responseCode = sh (
                        script: "curl -s -o /dev/null -w \"%{http_code}\" http://192.168.56.11:8080/greeting",
                        returnStdout: true
                    ).trim()

                    echo "Health Check HTTP response code: ${responseCode}"

                    if (responseCode != '200') {
                        error "Health check failed: Application is not responding correctly."
                    }
                }
            }
        }


        stage('Tag Stable Build') {
            when {
                expression {
                currentBuild.currentResult == 'SUCCESS'
            }
            }  
            steps {
                script {
                    sh """
                        git config user.name "jenkins"
                        git config user.email "jenkins@example.com"
                        git tag stable-v${BUILD_NUMBER}
                        git push origin stable-v${BUILD_NUMBER}
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully."
        }
        failure {
            echo "Pipeline failed."
        }
    }
}
