Vagrant.configure("2") do |config|

  # Machine take longer to boot
  config.vm.boot_timeout = 600

  # DB VM
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "cogsidb"
    db.vm.network "private_network", ip: "192.168.56.10"
    db.vm.provision "shell", path: "provision_db.sh"
  end

  # APP VM
  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/focal64"
    app.vm.hostname = "cogsiapp"
    app.vm.network "private_network", ip: "192.168.56.11"
    app.vm.provision "shell", path: "provision_app.sh"
  end
end
