- hosts: green
  become: yes
  vars:
    jenkins_url: "http://192.168.56.1:8080"
    jenkins_job_name: "CA6-Part1-Pipeline"

    jenkins_artifact_path: "CA6/Part1/spring-app/build/libs/rest-service-0.0.1-SNAPSHOT.jar"

    rollback_dir: "/vagrant/rollback"
    rollback_jar: "/vagrant/rollback/rest-service-rollback.jar"
    app_jar_dest: "/opt/app/app.jar"

  tasks:

    - name: Ensure rollback folder exists
      file:
        path: /vagrant/rollback
        state: directory

    - name: Download last successful artifact from Jenkins
      get_url:
        url: "{{ jenkins_url }}/job/{{ jenkins_job_name }}/lastSuccessfulBuild/artifact/{{ jenkins_artifact_path }}"
        dest: "{{ rollback_jar }}"
        mode: "0755"
        headers:
          Authorization: "Basic {{ (lookup('env','JENKINS_USER') + ':' + lookup('env','JENKINS_TOKEN')) | b64encode }}"
      register: download_result

    - name: Fail if rollback JAR does not exist
      stat:
        path: "{{ rollback_jar }}"
      register: rollback_file

    - name: Stop current spring-app service
      systemd:
        name: spring-app
        state: stopped
      when: rollback_file.stat.exists

    - name: Replace current application with rollback version
      copy:
        src: "{{ rollback_jar }}"
        dest: /opt/app/app.jar
        mode: '0755'
      when: rollback_file.stat.exists

    - name: Reload systemd daemon
      command: systemctl daemon-reload
      when: rollback_file.stat.exists

    - name: Start spring-app with rollback version
      systemd:
        name: spring-app
        state: started
        enabled: yes
      when: rollback_file.stat.exists

    - name: Health-check after rollback
      uri:
        url: "http://192.168.56.11:8080/greeting"
        return_content: yes
      register: health
      retries: 5
      delay: 5
      until: health.status == 200
      when: rollback_file.stat.exists
