Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 600
  config.ssh.insert_key = false
  config.vm.hostname = "ca3-vm"
  config.vm.network "forwarded_port", guest: 8080, host: 8080   # Spring Boot
  config.vm.network "forwarded_port", guest: 59001, host: 59001 # Chat app
  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "../h2data", "/home/vagrant/h2data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "provision.sh"
end
